version: '3.8'
services:
  web:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  php:
    build: .
    volumes:
      - ./src:/var/www/html